### ISSUE TITLE
Cannot run an app because the app is unable to start Kanela Agent

### ISSUE THREAD

**Issue by adinael** [kamon-io/kanela#116]
I am experiencing an error trying to run the [Block Explorer App](https://github.com/X9Developers/block-explorer) 
when i execute the `sbt run` command i get this error 
```
Unable to start Kanela Agent. Please remove -javaagent from your startup arguments and contact Kanela support.: java.lang.NoClassDefFoundError: Could not initialize class org.apache.logging.log4j.util.PropertiesUtil
	at org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.java:78)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:60)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at io.methvin.watcher.DirectoryWatcher$Builder.staticLogger(DirectoryWatcher.java:137)
	at io.methvin.watcher.DirectoryWatcher$Builder.build(DirectoryWatcher.java:115)
	at play.dev.filewatch.DefaultFileWatchService.watch(DefaultFileWatchService.scala:41)
	at play.dev.filewatch.FileWatchService$$anon$1.watch(FileWatchService.scala:90)
	at kamon.instrumentation.sbt.play.KanelaReloader.<init>(KanelaReloader.scala:408)
	at kamon.instrumentation.sbt.play.KanelaReloader$.reloader$lzycompute$1(KanelaReloader.scala:261)
	at kamon.instrumentation.sbt.play.KanelaReloader$.kamon$instrumentation$sbt$play$KanelaReloader$$reloader$1(KanelaReloader.scala:252)
	at kamon.instrumentation.sbt.play.KanelaReloader$$anon$3.get(KanelaReloader.scala:245)
	at play.runsupport.classloader.DelegatingClassLoader.getResources(DelegatingClassLoader.java:51)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1131)
	at kanela.agent.util.classloader.ChildFirstURLClassLoader.getResources(ChildFirstURLClassLoader.java:106)
	at kanela.agent.libs.com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:721)
	at kanela.agent.libs.com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:701)
	at kanela.agent.libs.com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at kanela.agent.libs.com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at kanela.agent.libs.com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
	at kanela.agent.libs.com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:185)
	at kanela.agent.libs.com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:133)
	at kanela.agent.libs.com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:1029)
	at kanela.agent.libs.com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:36)
	at kanela.agent.libs.com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:478)
	at kanela.agent.libs.com.typesafe.config.ConfigFactory.load(ConfigFactory.java:308)
	at kanela.agent.util.conf.KanelaConfiguration.loadDefaultConfig(KanelaConfiguration.java:304)
	at kanela.agent.util.conf.KanelaConfiguration.lambda$loadConfig$84c4dc62$1(KanelaConfiguration.java:261)
	at kanela.agent.libs.io.vavr.control.Try.of(Try.java:75)
	at kanela.agent.util.conf.KanelaConfiguration.loadConfig(KanelaConfiguration.java:261)
	at kanela.agent.util.conf.KanelaConfiguration.from(KanelaConfiguration.java:59)
	at kanela.agent.Kanela.lambda$null$0(Kanela.java:73)
	at kanela.agent.util.classloader.InstrumentationClassPath.use(InstrumentationClassPath.java:84)
	at kanela.agent.Kanela.lambda$start$1(Kanela.java:68)
	at kanela.agent.util.Execution.timed(Execution.java:32)
	at kanela.agent.util.Execution.runWithTimeSpent(Execution.java:41)
	at kanela.agent.Kanela.start(Kanela.java:67)
	at kanela.agent.Kanela.agentmain(Kanela.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411) 

```

**Comment by ivantopo** [comment]
Hey @adinael, I'm trying to run the app but SBT is giving me this error:

```
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.alexitc:playsonify-sql_2.12:2.2.0
[error]   Not found
[error]   Not found
[error]   not found: /home/ivantopo/.ivy2/local/com.alexitc/playsonify-sql_2.12/2.2.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/alexitc/playsonify-sql_2.12/2.2.0/playsonify-sql_2.12-2.2.0.pom
[error] Error downloading com.alexitc:playsonify-play_2.12:2.2.0
[error]   Not found
[error]   Not found
[error]   not found: /home/ivantopo/.ivy2/local/com.alexitc/playsonify-play_2.12/2.2.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/alexitc/playsonify-play_2.12/2.2.0/playsonify-play_2.12-2.2.0.pom
[error] Error downloading com.alexitc:playsonify-core_2.12:2.2.0
[error]   Not found
[error]   Not found
[error]   not found: /home/ivantopo/.ivy2/local/com.alexitc/playsonify-core_2.12/2.2.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/alexitc/playsonify-core_2.12/2.2.0/playsonify-core_2.12-2.2.0.pom
[error] Total time: 2 s, completed Feb 18, 2021, 6:07:40 PM
```

Are there any special settings I should be adding to be able to run the app?

**Comment by AlexITC** [comment]
Apparently we haven't documented that a custom version from [playsonify](https://github.com/AlexITC/playsonify) is required, see https://github.com/X9Developers/block-explorer/blob/develop/.circleci/config.yml#L37

**Comment by ivantopo** [comment]
I'm still investigating this issue, but here is something interesting: there was a change in the logging mechanisms underneath SBT since [SBT 1.4.0](https://github.com/sbt/sbt/releases/tag/v1.4.0) that triggers the issue. The actual problem is that the Typesafe Config library can't resolve the configuration because there is no ContextClassloader on the current thread (presumably, Log4j was taking care of that before). 

As a temporary measure you can add `ThisBuild / useLog4J := true` to your build and it will start working again. Will update later if/when I find a solution.

**Comment by ivantopo** [comment]
Hey folks, the issue should be fixed after upgrading to the sbt-kanela-runner version 2.0.9. Please give it a try and re-open if you keep seeing the issue!

**Comment by AlexITC** [comment]
That solved the issue, thanks!
