### ISSUE TITLE
Akka Instrumentation after update to 1.0.10

### ISSUE THREAD

**Issue by fggarcia** [kamon-io/kanela#122]
```
Exception in thread "main" java.lang.ExceptionInInitializerError
at kamon.instrumentation.akka.instrumentations.akka_26.InstrumentNewExecutorServiceOnAkka26$.around(DispatcherInstrumentation.scala:118)
at akka.dispatch.ForkJoinExecutorConfigurator$ForkJoinExecutorServiceFactory.createExecutorService(ForkJoinExecutorConfigurator.scala)
at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor$lzycompute(Dispatcher.scala:44)
at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.executor(Dispatcher.scala:44)
at akka.dispatch.ExecutorServiceDelegate.execute(ThreadPoolBuilder.scala:219)
at akka.dispatch.ExecutorServiceDelegate.execute$(ThreadPoolBuilder.scala:219)
at akka.dispatch.Dispatcher$LazyExecutorServiceDelegate.execute(Dispatcher.scala:43)
at akka.dispatch.Dispatcher.registerForExecution(Dispatcher.scala:127)
at akka.dispatch.MessageDispatcher.attach(AbstractDispatcher.scala:152)
at akka.actor.dungeon.Dispatch.start(Dispatch.scala:121)
at akka.actor.dungeon.Dispatch.start$(Dispatch.scala:119)
at akka.actor.ActorCell.start(ActorCell.scala:410)
at akka.actor.LocalActorRef.start(ActorRef.scala:384)
at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:605)
at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1026)
at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1022)
at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1022)
at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1045)
at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
at akka.actor.ActorSystem$.apply(ActorSystem.scala:260)
at com.despegar.zoom.ensemble.Ensemble.<init>(Ensemble.scala:71)
at com.despegar.zoom.server.ServerApp$.delayedEndpoint$com$despegar$zoom$server$ServerApp$1(ServerApp.scala:30)
at com.despegar.zoom.server.ServerApp$delayedInit$body.apply(ServerApp.scala:29)
at scala.Function0.apply$mcV$sp(Function0.scala:39)
at scala.Function0.apply$mcV$sp$(Function0.scala:39)
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
at scala.App.$anonfun$main$1(App.scala:76)
at scala.App.$anonfun$main$1$adapted(App.scala:76)
at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
at scala.App.main(App.scala:76)
at scala.App.main$(App.scala:74)
at com.despegar.zoom.server.ServerApp$.main(ServerApp.scala:29)
at com.despegar.zoom.server.ServerApp.main(ServerApp.scala)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.concurrent.ExecutorService java.util.concurrent.Executors$DelegatedExecutorService.e accessible: module java.base does not "opens java.util.concurrent" to unnamed module @6e4784bc
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
at kamon.instrumentation.executor.ExecutorInstrumentation$.<clinit>(ExecutorInstrumentation.scala:260)
... 36 more

```

**Comment by dpsoft** [comment]
@fggarcia workaround  `--illegal-access=permit`
