### ISSUE TITLE
jedis initialization causes java.lang.VerifyError

### ISSUE THREAD

**Issue by ashendon** [kamon-io/kanela#131]
hard crash in jedis 3.6.1, 3.6.0, 3.5.2 but not 2.9.0, with openJDK8u292 and openJDK11.0.11 the exact same way. Problem goes away when disabling kanela redis agent.

```
java.lang.VerifyError: Expecting a stackmap frame at branch target 20
Exception Details:
  Location:
    redis/clients/jedis/Protocol.sendCommand(Lredis/clients/jedis/util/RedisOutputStream;Lredis/clients/jedis/commands/ProtocolCommand;[[B)V @17: goto
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b201 c02b b601 c4a7 000e 1301 c65f b801
    0000010: cca7 0003 014e 2a3a 042b 3a05 2c3a 0619
    0000020: 0419 05b9 0002 0100 1906 b800 03a7 0003
    0000030: 013a 04a7 0005 3a04 b201 c02d 1904 b601
    0000040: d2a7 000d 1301 c65f b801 cca7 0003 1904
    0000050: c600 0619 04bf b1                      
  Exception Handler Table:
    bci [0, 10] => handler: 10
    bci [31, 48] => handler: 54
    bci [56, 68] => handler: 68
  Stackmap Table:
    same_locals_1_stack_item_frame(@10,Object[#442])
    same_locals_1_stack_item_frame(@21,Object[#462])
    append_frame(@22,Object[#462])
    append_frame(@31,Object[#279],Object[#275],Object[#217])
    full_frame(@48,{Object[#279],Object[#275],Object[#217],Object[#462]},{})
    same_locals_1_stack_item_frame(@54,Object[#442])
    append_frame(@56,Object[#442])
    same_locals_1_stack_item_frame(@68,Object[#442])
    same_frame(@78)
    same_frame(@86)

	at redis.clients.jedis.Connection.sendCommand(Connection.java:164)
	at redis.clients.jedis.BinaryClient.cluster(BinaryClient.java:1442)
	at redis.clients.jedis.Client.cluster(Client.java:1168)
	at redis.clients.jedis.Client.clusterSlots(Client.java:1267)
	at redis.clients.jedis.Jedis.clusterSlots(Jedis.java:3921)
	at redis.clients.jedis.JedisClusterInfoCache.discoverClusterNodesAndSlots(JedisClusterInfoCache.java:145)
	at redis.clients.jedis.JedisClusterConnectionHandler.initializeSlotsCache(JedisClusterConnectionHandler.java:127)
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:100)
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:79)
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:40)
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:34)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:41)
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:81)
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:74)
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:68)
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:63)
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:58)
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:146)
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:132)
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:128)
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:124)
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:29)
```

**Comment by ashendon** [comment]
only occurs in 1.0.9 not 1.0.11
