### ISSUE TITLE
v1.0.18 - Java 21 Unsupported class file major version 65

### ISSUE THREAD

**Issue by anujprashar** [kamon-io/kanela#154]
@nvollmar We are getting error for v1.0.18 with Java 21.
←[31m[main] ERROR ←[90m2023-11-02 18:59:45  ←[38;5;24mLogger ←[97m: ←[10mError => scala.util.Success with message Unsupported class file major version 65. Class loader: jdk.internal.loader.ClassLoaders$AppClassLoader@2c7b84de: java.lang.IllegalArgumentException: Unsupported class file major version 65
        at kanela.agent.libs.net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:196)
        at kanela.agent.libs.net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:177)
        at kanela.agent.libs.net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:163)
        at kanela.agent.libs.net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:86)
        at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:679)
        at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:665)
        at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$001(TypePool.java:745)
        at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:843)
        at kanela.agent.libs.net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:912)
        at kanela.agent.libs.net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8339)
        at kanela.agent.libs.net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
        at kanela.agent.libs.net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)

**Comment by danischroeter** [comment]
fixed in 2.0.0
@ivantopo can be closed
