### ISSUE TITLE
NPE when instrumenting logback appender pool 

### ISSUE THREAD

**Issue by fgaule** [kamon-io/kanela#65]
I'm using [FluencyLogbackAppender](https://github.com/sndyuk/logback-more-appenders) to report events to FluentD and i'm getting a NPE when Kanela tries to instrument a pool used by [Fluency](https://github.com/komamitsu/fluency).

```01:39:12,453 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FLUENCY]
01:39:19,511 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@110:13 - RuntimeException in Action for tag [appender] java.lang.RuntimeException: java.lang.NullPointerException
	at java.lang.RuntimeException: java.lang.NullPointerException
	at 	at ch.qos.logback.more.appenders.FluencyLogbackAppender.start(FluencyLogbackAppender.java:47)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at kamon.Kamon$.<init>(Kamon.scala:33)
	at 	at kamon.Kamon$.<clinit>(Kamon.scala)
	at 	at kamon.Kamon.currentContext(Kamon.scala)
	at 	at kamon.executors.instrumentation.ExecutorInstrumentation$ContextAwareCallable.<init>(ExecutorInstrumentation.java:100)
	at 	at kamon.executors.instrumentation.ExecutorInstrumentation$KamonContextProvider.wrapInContextAware(ExecutorInstrumentation.java:125)
	at 	at kanela.agent.bootstrap.context.ContextHandler.wrapInContextAware(ContextHandler.java:52)
	at 	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:681)
	at 	at com.newrelic.agent.utilization.UtilizationService.scheduleUtilizationTask(UtilizationService.java:96)
	at 	at com.newrelic.agent.utilization.UtilizationService.doStart(UtilizationService.java:87)
	at 	at com.newrelic.agent.service.AbstractService.start(AbstractService.java:56)
	at 	at com.newrelic.agent.service.ServiceManagerImpl.doStart(ServiceManagerImpl.java:174)
	at 	at com.newrelic.agent.service.AbstractService.start(AbstractService.java:56)
	at 	at com.newrelic.agent.Agent.premain(Agent.java:319)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.lang.reflect.Method.invoke(Method.java:498)
	at 	at com.newrelic.bootstrap.BootstrapAgent.startAgent(BootstrapAgent.java:160)
	at 	at com.newrelic.bootstrap.BootstrapAgent.premain(BootstrapAgent.java:66)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.lang.reflect.Method.invoke(Method.java:498)
	at 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at 	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NullPointerException
	at 	at kamon.Kamon$.currentContext(Kamon.scala:109)
	at 	at kamon.Kamon.currentContext(Kamon.scala)
	at 	at kamon.executors.instrumentation.ExecutorInstrumentation$ContextAwareRunnable.<init>(ExecutorInstrumentation.java:76)
	at 	at kamon.executors.instrumentation.ExecutorInstrumentation$KamonContextProvider.wrapInContextAware(ExecutorInstrumentation.java:120)
	at 	at kanela.agent.bootstrap.context.ContextHandler.wrapInContextAware(ContextHandler.java:51)
	at 	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668)
	at 	at org.komamitsu.fluency.flusher.AsyncFlusher.<init>(AsyncFlusher.java:78)
	at 	at org.komamitsu.fluency.flusher.AsyncFlusher.<init>(AsyncFlusher.java:32)
	at 	at org.komamitsu.fluency.flusher.AsyncFlusher$Config.createInstance(AsyncFlusher.java:174)
	at 	at org.komamitsu.fluency.flusher.AsyncFlusher$Config.createInstance(AsyncFlusher.java:120)
	at 	at org.komamitsu.fluency.Fluency$Builder.build(Fluency.java:449)
	at 	at org.komamitsu.fluency.Fluency.buildDefaultFluency(Fluency.java:163)
	at 	at org.komamitsu.fluency.Fluency.defaultFluency(Fluency.java:182)
	at 	at ch.qos.logback.more.appenders.FluencyLogbackAppender.start(FluencyLogbackAppender.java:45)
	at 	... 42 common frames omitted
```

Dependencies:
```
"com.sndyuk"                %   "logback-more-appenders"  % "1.4.3",
"org.komamitsu"             %   "fluency"                 % "1.8.1",
"io.kamon"                  %   "kanela-agent-bundle"     % "0.0.14"           % "agent",
"io.kamon"                  %%  "kamon-core"              % "1.1.3",
"io.kamon"                  %%  "kanela-scala-extension"  % "0.0.14",
"io.kamon"                  %%  "kamon-servlet-3"         % "1.0.0",
"io.kamon"                  %%  "kamon-jaeger"            % "1.0.2",
"io.kamon"                  %%  "kamon-zipkin"            % "1.0.0",
"io.kamon"                  %%  "kamon-prometheus"        % "1.1.1",
"io.kamon"                  %   "kamon-annotation-api"    % "1.0.3",
```
Config
```
kamon {
  environment.service = "bkd-connect"
  trace.sampler = "never"
  trace.join-remote-parents-with-same-span-id = true
  reporters = []
}

kanela {
  show-banner = false
  log-level = "ERROR"
  modules {
    annotation-module.within = [ "com.despegar.bookedia..*" ]

    mariadb-module {
      name = "MariaDB Instrumentation Module"
      instrumentations = [
        "com.despegar.bookedia.connect.monitoring.instrumentation.MariaDBInstrumentation"
      ]
      within = [
        "org.mariadb.jdbc..*"
      ]
    }
  }
}
```

Cheers!

**Comment by dpsoft** [comment]
fixed with: kamon-io/kamon-logback@8d3d5fb
