### ISSUE TITLE
ClassCastException when using logback-access

### ISSUE THREAD

**Issue by fgaule** [kamon-io/kanela#66]
Logback Access: https://logback.qos.ch/access.html
Kanela version: 0.0.14
Kamon versions:
    "io.kamon"                  %   "kanela-agent-bundle"     % KanelaVersion           % "agent",
    "io.kamon"                  %%  "kamon-core"              % "1.1.3",
    "io.kamon"                  %%  "kanela-scala-extension"  % "0.0.14",
    "io.kamon"                  %%  "kamon-servlet-3"         % "1.0.0",
    "io.kamon"                  %%  "kamon-jaeger"            % "1.0.2",
    "io.kamon"                  %%  "kamon-zipkin"            % "1.0.0",
    "io.kamon"                  %%  "kamon-prometheus"        % "1.1.1",
    "io.kamon"                  %   "kamon-annotation-api"    % "1.0.3",

Jetty config
```scala
private def configureHandlers(): Unit = {
    jettyServer.setHandler {
      val handlers = new HandlerCollection()

      handlers.addHandler {

        val contextHandler = new ServletContextHandler()
        contextHandler setContextPath contextPath
        contextHandler.setInitParameter(ScalatraListener.LifeCycleKey, "com.despegar.bookedia.connect.server.ScalatraBootstrap")
        contextHandler.addEventListener(new ScalatraListener)
        contextHandler.addServlet(classOf[DefaultServlet], "/")
        contextHandler.addFilter(new FilterHolder(new TeeFilter()), "/*", util.EnumSet.of(DispatcherType.INCLUDE, DispatcherType.REQUEST, DispatcherType.FORWARD))
        contextHandler.addFilter(new FilterHolder(new MaintenanceFilter()), "/*", util.EnumSet.of(DispatcherType.INCLUDE, DispatcherType.REQUEST, DispatcherType.FORWARD))

        val requestLogHandler = new RequestLogHandler
        val requestLog = new RequestLogImpl
        requestLog.setResource("/logback-access.xml")
        requestLogHandler.setRequestLog(requestLog)
        requestLogHandler.setHandler(contextHandler)

        requestLogHandler
      }
      handlers
    }
  }
```
Exception when starting app:
```java 
java.lang.ClassCastException: ch.qos.logback.access.spi.AccessEvent cannot be cast to kamon.logback.instrumentation.ContextAwareLoggingEvent
	at kamon.logback.instrumentation.kanela.AppendLoopMethodInterceptor$.aroundAppendLoop(AsyncAppenderInstrumentation.scala:100)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java)
	at ch.qos.logback.access.jetty.RequestLogImpl.log(RequestLogImpl.java:137)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:104)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
	at org.eclipse.jetty.server.Server.handle(Server.java:461)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by dpsoft** [comment]
fixed with: https://github.com/kamon-io/kamon-logback/pull/11/commits/8d3d5fb8c1cfca0eadae26af5e7e7765c77ef5ae
