### ISSUE TITLE
Using @Initializer on a mixin fails with Scala 2.11

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/kanela#67]
This came up when trying to upgrade the Scalaz Future instrumentation. Here is the stacktrace we were getting:

```
[error] Uncaught exception when running kamon.scalaz.instrumentation.FutureInstrumentationSpec: java.lang.VerifyError: Bad type on operand stack
[error] Exception Details:
[error]   Location:
[error]     scalaz/concurrent/Future$$anonfun$apply$15$$anon$3.<init>(Lscalaz/concurrent/Future$$anonfun$apply$15;Lscala/Function1;)V @6: invokevirtual
[error]   Reason:
[error]     Type uninitializedThis (current frame, stack[1]) is not assignable to 'scalaz/concurrent/Future$$anonfun$apply$15$$anon$3'
[error]   Current Frame:
[error]     bci: @6
[error]     flags: { flagThisUninit }
[error]     locals: { uninitializedThis, 'scalaz/concurrent/Future$$anonfun$apply$15', 'scala/Function1' }
[error]     stack: { null, uninitializedThis }
[error]   Bytecode:
[error]     0x0000000: 2bc7 0009 012a b600 68bf 2a2b b500 142a
[error]     0x0000010: 2cb5 0012 2ab7 0041 2ab6 0068 b1       
[error]   Stackmap Table:
[error]     same_frame(@10)
[error] sbt.ForkMain$ForkError: java.lang.VerifyError: Bad type on operand stack
[error] Exception Details:
[error]   Location:
[error]     scalaz/concurrent/Future$$anonfun$apply$15$$anon$3.<init>(Lscalaz/concurrent/Future$$anonfun$apply$15;Lscala/Function1;)V @6: invokevirtual
[error]   Reason:
[error]     Type uninitializedThis (current frame, stack[1]) is not assignable to 'scalaz/concurrent/Future$$anonfun$apply$15$$anon$3'
[error]   Current Frame:
[error]     bci: @6
[error]     flags: { flagThisUninit }
[error]     locals: { uninitializedThis, 'scalaz/concurrent/Future$$anonfun$apply$15', 'scala/Function1' }
[error]     stack: { null, uninitializedThis }
[error]   Bytecode:
[error]     0x0000000: 2bc7 0009 012a b600 68bf 2a2b b500 142a
[error]     0x0000010: 2cb5 0012 2ab7 0041 2ab6 0068 b1       
[error]   Stackmap Table:
[error]     same_frame(@10)
[error] 
[error] 	at scalaz.concurrent.Future$$anonfun$apply$15.apply(Future.scala:432)
[error] 	at scalaz.concurrent.Future$$anonfun$apply$15.apply(Future.scala:431)
[error] 	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:77)
[error] 	at scalaz.concurrent.Future.unsafePerformAsync(Future.scala:159)
[error] 	at scalaz.concurrent.Future.unsafeStart(Future.scala:144)
[error] 	at kamon.scalaz.instrumentation.FutureInstrumentationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$2.apply(FutureInstrumentationSpec.scala:38)
[error] 	at kamon.scalaz.instrumentation.FutureInstrumentationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$2.apply(FutureInstrumentationSpec.scala:38)
[error] 	at kamon.ContextStorage$class.withContext(ContextStorage.scala:23)
[error] 	at kamon.Kamon$.withContext(Kamon.scala:18)
[error] 	at kamon.scalaz.instrumentation.FutureInstrumentationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(FutureInstrumentationSpec.scala:37)
[error] 	at kamon.scalaz.instrumentation.FutureInstrumentationSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(FutureInstrumentationSpec.scala:34)
[error] 	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[error] 	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:22)
[error] 	at org.scalatest.Transformer.apply(Transformer.scala:20)
[error] 	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[error] 	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[error] 	at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[error] 	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[error] 	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[error] 	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[error] 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[error] 	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[error] 	at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[error] 	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[error] 	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[error] 	at scala.collection.immutable.List.foreach(List.scala:381)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[error] 	at scala.collection.immutable.List.foreach(List.scala:381)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[error] 	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[error] 	at scala.collection.immutable.List.foreach(List.scala:381)
[error] 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[error] 	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[error] 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[error] 	at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[error] 	at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[error] 	at org.scalatest.Suite$class.run(Suite.scala:1147)
[error] 	at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[error] 	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[error] 	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[error] 	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[error] 	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[error] 	at org.scalatest.WordSpec.run(WordSpec.scala:1881)
[error] 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[error] 	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

And the instrumentation was looking like this:

```scala
class FutureInstrumentation extends KanelaInstrumentation {
   forSubtypeOf("java.util.concurrent.Callable") { builder ⇒
    builder
      .withMixin(classOf[HasContextMixin])
      .withAdvisorFor(method("call"), classOf[RunMethodAdvisor])
      .build()
  }
}
 class HasContextMixin extends HasContext {
  private var _context: Context = _
   @Initializer
  def initialize(): Unit =
    _context = Kamon.currentContext()
   override def context: Context =
    _context
}
 class RunMethodAdvisor
object RunMethodAdvisor {
   @Advice.OnMethodEnter
  def enter(@Advice.This hasContext: HasContext): Storage.Scope =
    Kamon.storeContext(hasContext.context)
   @Advice.OnMethodExit(onThrowable = classOf[Throwable])
  def exit(@Advice.Enter scope: Storage.Scope): Unit =
    scope.close()
}
```

**Comment by ivantopo** [comment]
I'm not really sure if it is the same issue, but I just found out that `@Initializer` breaks with a very similar exception if the target type for the Mixin is an Inner class in Scala. See this example:

```scala
class Processor {
  // ... more stuff
  class SubmittedTaskInner[T](val promise: Promise[T], task: Task[T]) extends Task[T] {
    println("This is some constructor code")

    override def run(): T = task.run()
  }
  // ... more stuff
}

object Processor {
  class SubmittedTask[T](val promise: Promise[T], task: Task[T]) extends Task[T] {
    println("This is some constructor code")
    override def run(): T = task.run()
  }

  trait Task[T] {
    def run(): T
  }
}
```

I was trying to make a mixin that targets subtypes of `Processor.Task`; when using `Processor.SubmittedTask` from the companion object it all works fine but when using `Processor.SubmittedTaskInner` from another function inside the `Processor` class it breaks with this exception:

```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    kamon/Processor$SubmittedTaskInner.<init>(Lkamon/Processor;Lscala/concurrent/Promise;Lkamon/Processor$Task;)V @16: invokevirtual
  Reason:
    Type uninitializedThis (current frame, stack[1]) is not assignable to 'kamon/Processor$SubmittedTaskInner'
  Current Frame:
    bci: @16
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'kamon/Processor', 'scala/concurrent/Promise', 'kamon/Processor$Task' }
    stack: { null, uninitializedThis }
  Bytecode:
    0x0000000: 2a2c b500 182a 2db5 001f 2bc7 0009 012a
    0x0000010: b600 47bf 2a2b b500 252a b700 2bb2 0031
    0x0000020: 1233 b600 372a b600 47b1               
  Stackmap Table:
    same_frame(@20)

	at kamon.Processor.submit(Targets.scala:27)
	at kamon.instrumentation.MixinMinimalRunner$.delayedEndpoint$kamon$instrumentation$MixinMinimalRunner$1(MixinMinimal.scala:40)
	at kamon.instrumentation.MixinMinimalRunner$delayedInit$body.apply(MixinMinimal.scala:34)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at kamon.instrumentation.MixinMinimalRunner$.main(MixinMinimal.scala:34)
	at kamon.instrumentation.MixinMinimalRunner.main(MixinMinimal.scala)


```
