### ISSUE TITLE
Error while starting application with kanela happens sometimes

### ISSUE THREAD

**Issue by xeppaka** [kamon-io/kanela#90]
During application startup sometimes the following exception occurred java.lang.ClassCircularityError. Is it some kanela issue?

```
 _  __                _        ______
| |/ /               | |       \ \ \ \
| ' / __ _ _ __   ___| | __ _   \ \ \ \
|  < / _` | '_ \ / _ \ |/ _` |   ) ) ) )
| . \ (_| | | | |  __/ | (_| |  / / / /
|_|\_\__,_|_| |_|\___|_|\__,_| /_/_/_/
                              
==============================
[32;1mRunning with Kanela, the Kamon Instrumentation Agent :: (v1.0.1)[0m

[31m[kamon-agent-strategy-cache-listener-1] ERROR [90m2019-09-04 08:16:06  [38;5;24mLogger [97m: [10mError => java.util.concurrent.locks.LockSupport with message java/util/concurrent/locks/LockSupport. Class loader: Bootstrap ClassLoader: java.lang.ClassCircularityError: java/util/concurrent/locks/LockSupport
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
	at kanela.agent.libs.net.jodah.expiringmap.ExpiringMap.getEntry(ExpiringMap.java:1243)
	at kanela.agent.libs.net.jodah.expiringmap.ExpiringMap.get(ExpiringMap.java:742)
	at kanela.agent.cache.PoolStrategyCache.locate(PoolStrategyCache.java:56)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$PoolStrategy$WithTypePoolCache.typePool(AgentBuilder.java:2815)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10512)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10280)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10890)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10837)
	at java.security.AccessController.doPrivileged(Native Method)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10437)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)[0m 
08:16:08,425 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
08:16:08,427 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
08:16:08,427 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/opt/cif-gen/conf/logback.xml]
08:16:08,429 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
08:16:08,429 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/opt/cif-gen/conf/logback.xml]
08:16:08,429 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/opt/cif-gen/lib/com.finfactory.cif.cif-gen-1.0-r29.jar!/logback.xml]
08:16:08,655 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
08:16:08,689 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/opt/cif-gen/conf/logback.xml] 
08:16:08,689 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 1 minutes
08:16:08,692 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word contextEntry with class [kamon.instrumentation.logback.tools.ContextEntryConverter]
08:16:08,693 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
08:16:08,713 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
08:16:08,757 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1443675930 - setting totalSizeCap to 500 MB
08:16:08,766 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1443675930 - Archive files will be limited to [50 MB] each.
08:16:08,805 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1443675930 - Will use gz compression
08:16:08,840 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1443675930 - Will use the pattern /var/log/cif-gen/cif-gen.log.%d{yyyy-MM-dd}.%i for the active file
08:16:08,844 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@5fe8b721 - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/cif-gen/cif-gen.log.%d{yyyy-MM-dd}.%i.gz'.
08:16:08,844 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@5fe8b721 - Roll-over at midnight.
08:16:08,860 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@5fe8b721 - Setting initial period to Wed Sep 04 08:16:06 UTC 2019
08:16:08,870 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:16:08,959 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /var/log/cif-gen/cif-gen.log
08:16:08,959 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/var/log/cif-gen/cif-gen.log]
08:16:08,965 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
08:16:09,314 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC_FILE]
08:16:09,314 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to ch.qos.logback.classic.AsyncAppender[ASYNC_FILE]
08:16:09,314 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_FILE] - Attaching appender named [FILE] to AsyncAppender.
08:16:09,315 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_FILE] - Setting discardingThreshold to 51
08:16:09,319 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
08:16:09,319 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_FILE] to Logger[ROOT]
08:16:09,321 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.finfactory] to INFO
08:16:09,321 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [eu.akkamo.AkkaHttpModule] to INFO
08:16:09,321 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
08:16:09,322 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@551a20d6 - Registering current configuration as safe fallback point

[31m[main] ERROR [90m2019-09-04 08:16:10  [38;5;24mLogger [97m: [10mError => com.google.common.collect.Maps with message java/util/concurrent/locks/LockSupport. Class loader: sun.misc.Launcher$AppClassLoader@14dad5dc: java.lang.ClassCircularityError: java/util/concurrent/locks/LockSupport
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
	at kanela.agent.libs.net.jodah.expiringmap.ExpiringMap.getEntry(ExpiringMap.java:1243)
	at kanela.agent.libs.net.jodah.expiringmap.ExpiringMap.get(ExpiringMap.java:742)
	at kanela.agent.cache.PoolStrategyCache.locate(PoolStrategyCache.java:56)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$PoolStrategy$WithTypePoolCache.typePool(AgentBuilder.java:2815)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10512)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10280)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10890)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10837)
	at java.security.AccessController.doPrivileged(Native Method)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10437)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.inject.internal.CycleDetectingLock$CycleDetectingLockFactory.<clinit>(CycleDetectingLock.java:85)
	at com.google.inject.internal.Initializer.<init>(Initializer.java:51)
	at com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:63)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at com.finfactory.cif.generic.modules.GenericApp.<init>(GenericApp.scala:38)
	at com.finfactory.cif.generic.modules.GenericApp$.main(GenericApp.scala:82)
	at com.finfactory.cif.generic.modules.GenericApp.main(GenericApp.scala)[0m 
Exception in thread "kamon-scheduler-1" java.lang.ClassCircularityError: java/util/concurrent/locks/LockSupport
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.unparkSuccessor(AbstractQueuedSynchronizer.java:662)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1264)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1104)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "kamon-scheduler-3" java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signal(AbstractQueuedSynchronizer.java:1939)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1103)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Uncaught error from thread [application-akka.actor.default-dispatcher-2]: java/util/concurrent/locks/LockSupport, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.ClassCircularityError: java/util/concurrent/locks/LockSupport
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.unparkSuccessor(AbstractQueuedSynchronizer.java:662)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1264)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:356)
	at ch.qos.logback.core.AsyncAppenderBase.putUninterruptibly(AsyncAppenderBase.java:181)
	at ch.qos.logback.core.AsyncAppenderBase.put(AsyncAppenderBase.java:172)
	at ch.qos.logback.core.AsyncAppenderBase.append(AsyncAppenderBase.java:161)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders$original$Bp07aQdf(AppenderAttachableImpl.java:51)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders$original$Bp07aQdf$accessor$gGlSLLus(AppenderAttachableImpl.java)
	at ch.qos.logback.core.spi.AppenderAttachableImpl$auxiliary$RUIZdJ7z.call(Unknown Source)
	at kamon.instrumentation.logback.AppendLoopMethodInterceptor$.$anonfun$aroundAppendLoop$1(LogbackInstrumentation.scala:83)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:12)
	at kamon.ContextStorage.runWithContext(ContextStorage.scala:67)
	at kamon.ContextStorage.runWithContext$(ContextStorage.scala:64)
	at kamon.Kamon$.runWithContext(Kamon.scala:19)
	at kamon.instrumentation.logback.AppendLoopMethodInterceptor$.aroundAppendLoop(LogbackInstrumentation.scala:83)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.info(Logger.java:579)
	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:101)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:55)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedForkJoinPool$TimingRunnable.run(ExecutorInstrumentation.scala:653)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by dpsoft** [comment]
I think that pre-initializing `java.util.concurrent.locks.ReentrantReadWriteLock` to avoid this error, but I need make some tests.

Related Info:
-- http://mail.openjdk.java.net/pipermail/hotspot-dev/2012-March/005464.html
 Sometimes (at least prior to parallel class loading in JDK 7) initializing other classes inside of a `ClassFileTransformer.transform()` method occasionally leads to deadlocks.

**Comment by DReigada** [comment]
I seems that this agent solved the same issue by pre-initializing some classes. https://github.com/glowroot/glowroot/blob/master/agent/core/src/main/java/org/glowroot/agent/weaving/PreInitializeWeavingClasses.java#L27

**Comment by ggalves** [comment]
I'm with the same issue

**Comment by dpsoft** [comment]
@ggalves please take a look: https://github.com/kamon-io/kanela/pull/91

**Comment by ggalves** [comment]
@dpsoft how can i try this version?

I'm using Kamon this way:

```scala
libraryDependencies += "io.kamon" %% "kamon-bundle" % "2.0.4"

lazy val root = (project in file(".")).enablePlugins(PlayScala, JavaAgent)
```

**Comment by dpsoft** [comment]
@ggalves you need start your application with `-javaagent:1.0.2-a0043b8e27b8dea831c5181daab3e0e3eed7abd1.jar`

**Comment by ggalves** [comment]
@dpsoft thanks!

but the snapshot failed for me... I received a lot of ClassNotFoundException, and at the end, i got the same lock problem

here is some of the ClassNotFoundException (there was more than this)

```
[main] ERROR 2019-11-25 19:03:03  Logger : kanela.agent.libs.net.bytebuddyagent.builder.AgentBuilder: java.lang.ClassNotFoundException: kanela.agent.libs.net.bytebuddyagent.builder.AgentBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at kanela.agent.util.classloader.PreInitializeClasses.initialize(PreInitializeClasses.java:60)
	at kanela.agent.util.classloader.PreInitializeClasses.preInitializeClasses(PreInitializeClasses.java:52)
	at kanela.agent.Kanela.start(Kanela.java:65)
	at kanela.agent.Kanela.premain(Kanela.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
[main] ERROR 2019-11-25 19:03:03  Logger : kanela.agent.libs.net.bytebuddyagent.builder.AgentBuilder.Listener: java.lang.ClassNotFoundException: kanela.agent.libs.net.bytebuddyagent.builder.AgentBuilder.Listener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at kanela.agent.util.classloader.PreInitializeClasses.initialize(PreInitializeClasses.java:60)
	at kanela.agent.util.classloader.PreInitializeClasses.preInitializeClasses(PreInitializeClasses.java:52)
	at kanela.agent.Kanela.start(Kanela.java:65)
	at kanela.agent.Kanela.premain(Kanela.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
[main] ERROR 2019-11-25 19:03:03  Logger : kanela.agent.libs.net.bytebuddyagent.builder.AgentBuilder.RedefinitionStrategy.ResubmissionScheduler: java.lang.ClassNotFoundException: kanela.agent.libs.net.bytebuddyagent.builder.AgentBuilder.RedefinitionStrategy.ResubmissionScheduler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at kanela.agent.util.classloader.PreInitializeClasses.initialize(PreInitializeClasses.java:60)
	at kanela.agent.util.classloader.PreInitializeClasses.preInitializeClasses(PreInitializeClasses.java:52)
	at kanela.agent.Kanela.start(Kanela.java:65)
	at kanela.agent.Kanela.premain(Kanela.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
[main] ERROR 2019-11-25 19:03:03  Logger : kanela.agent.libs.net.bytebuddyagent.builder.ResettableClassFileTransformer: java.lang.ClassNotFoundException: kanela.agent.libs.net.bytebuddyagent.builder.ResettableClassFileTransformer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at kanela.agent.util.classloader.PreInitializeClasses.initialize(PreInitializeClasses.java:60)
	at kanela.agent.util.classloader.PreInitializeClasses.preInitializeClasses(PreInitializeClasses.java:52)
	at kanela.agent.Kanela.start(Kanela.java:65)
	at kanela.agent.Kanela.premain(Kanela.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
```

**Comment by dpsoft** [comment]
@ggalves I'm going to do another snapshot give me a couple of hours..

**Comment by dpsoft** [comment]
@ggalves I've just published a new snapshot version of kanela : https://bintray.com/kamon-io/snapshots/kanela/1.0.4-a22440f76424ba69c4f16afd4ce36c1abf699aee can you try with this?

**Comment by dpsoft** [comment]
@ggalves I've just published a new snapshot version of kanela : https://bintray.com/kamon-io/snapshots/download_file?file_path=io%2Fkamon%2Fkanela-agent%2F1.0.5-a22440f76424ba69c4f16afd4ce36c1abf699aee%2Fkanela-agent-1.0.5-a22440f76424ba69c4f16afd4ce36c1abf699aee.jar can you try with this?

**Comment by ggalves** [comment]
hey @dpsoft, i've tried here and seems to work nice.

But as @xeppaka said, the problem only occurred sometimes. I'll keep trying to reproduce the problem a little more, and if it happens, I can alert it here. If you know any better ways to test than just testing on startup, let me know.

Thanks!

**Comment by ggalves** [comment]
@dpsoft I keep with the issue

```
 _  __                _        ______
| |/ /               | |       \ \ \ \
| ' / __ _ _ __   ___| | __ _   \ \ \ \
|  < / _` | '_ \ / _ \ |/ _` |   ) ) ) )
| . \ (_| | | | |  __/ | (_| |  / / / /
|_|\_\__,_|_| |_|\___|_|\__,_| /_/_/_/

==============================
Running with Kanela, the Kamon Instrumentation Agent :: (v1.0.5-a22440f76424ba69c4f16afd4ce36c1abf699aee)

[ExpiringMap-Expirer] ERROR 2019-11-28 13:20:48  Logger : Error => java.util.concurrent.locks.LockSupport with message java/util/concurrent/locks/LockSupport. Class loader: Bootstrap ClassLoader: java.lang.ClassCircularityError: java/util/concurrent/locks/LockSupport
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
	at kanela.agent.libs.net.jodah.expiringmap.ExpiringMap.getEntry(ExpiringMap.java:1243)
	at kanela.agent.libs.net.jodah.expiringmap.ExpiringMap.get(ExpiringMap.java:742)
	at kanela.agent.cache.PoolStrategyCache.locate(PoolStrategyCache.java:56)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$PoolStrategy$WithTypePoolCache.typePool(AgentBuilder.java:2813)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10455)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10223)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10833)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10780)
	at java.security.AccessController.doPrivileged(Native Method)
	at kanela.agent.libs.net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10380)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dpsoft** [comment]
@ggalves I've just published a new snapshot version of kanela : https://bintray.com/kamon-io/snapshots/download_file?file_path=io%2Fkamon%2Fkanela-agent%2F1.0.7-a22440f76424ba69c4f16afd4ce36c1abf699aee%2Fkanela-agent-1.0.7-a22440f76424ba69c4f16afd4ce36c1abf699aee.jar you can try with this? Anyway I need find a way of reproduce this issue in order to fix this with a better approach.

**Comment by dpsoft** [comment]
related to #91

**Comment by mladens** [comment]
This one seems ok.

I package a small app with one instrumented class and just run a bunch of them in parallel, it throws almost every time for 50-ish runs. This one works so far :)

**Comment by dpsoft** [comment]
@mladens  nice :) the only change that I maked was also pre-load `java.util.concurrent.locks.LockSupport` and I think that does the trick

**Comment by ggalves** [comment]
@dpsoft I'm trying it now. In first run everything went fine

**Comment by ggalves** [comment]
@dpsoft I couldn't reproduce it anymore. Looks ok for me too :)

**Comment by ggalves** [comment]
can you notify here when this fix is released?

**Comment by dpsoft** [comment]
@ggalves Yes, of course.

**Comment by dpsoft** [comment]
@ggalves ping!! https://github.com/kamon-io/kanela/releases/tag/v1.0.4

**Comment by ggalves** [comment]
Nice work, @dpsoft ! Thank you so much!
